# cargo-audit configuration.
# https://docs.rs/cargo-audit/latest/cargo_audit/config/index.html
[advisories]
informational_warnings = ["unmaintained"]
ignore = [
    # Ignoring for RSA as not possible to use in timing attack
    # And no fix available.
    "RUSTSEC-2023-0071",
]
