name: Docker Image Audit

on:
  workflow_run:
    workflows: ["Release Docker"] # Must exactly match the name of the first workflow
    types:
      - completed
  schedule:
    # (SOC2 continuous monitoring).
    - cron: "0 12 * * *"
  workflow_dispatch: {}

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: Pull Docker Image from GHCR
        run: |
          docker pull ghcr.io/hastehealth/hastehealth/hastehealth:latest
      - name: Scan server image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/hastehealth/hastehealth/hastehealth:latest
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          exit-code: "1"
          format: table

  admin-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: Pull Docker Image from GHCR
        run: |
          docker pull ghcr.io/hastehealth/hastehealth/hastehealth:latest
      - name: Scan admin-app image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/hastehealth/hastehealth/hastehealth:latest
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          exit-code: "1"
          format: table
