name: Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check --verbose
        working-directory: ./backend

      - name: Run clippy
        working-directory: ./backend
        run: |
          cargo clippy --no-deps \
          -p haste-access-control \
          -p haste-artifacts \
          -p haste-codegen \
          -p haste-config \
          -p haste-encryption \
          -p haste-fhir-client \
          -p haste-fhir-converter \
          -p haste-fhir-generated-ops \
          -p haste-fhir-operation-error \
          -p haste-fhir-operation-error-derive \
          -p haste-fhir-ops \
          -p haste-fhir-ops-derive \
          -p haste-fhir-profiling \
          -p haste-fhir-search \
          -p haste-fhir-serialization-json \
          -p haste-fhir-serialization-json-derive \
          -p haste-fhir-subscription-processor \
          -p haste-fhir-terminology \
          -p haste-fhirpath \
          -p haste-hl7v2 \
          -p haste-jwt \
          -p haste-macro-loads \
          -p haste-openapi-schema-generator \
          -p haste-operation-executor \
          -p haste-pointer \
          -p haste-rate-limit \
          -p haste-reflect \
          -p haste-reflect-derive \
          -p haste-repository \
          -p haste-sd-to-json-schema \
          -p haste-sql-on-fhir \
          -p haste-testscript-runner \
          -p haste-wal-worker \
          -p haste-worker \
          -p haste-x-fhir-query \
          -- -Dclippy::all -Dclippy::pedantic

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-key"
          workspaces: "./backend -> target"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Unit tests
        run: cargo test --locked --verbose --workspace
        working-directory: ./backend
